os: osx
osx_image: xcode7.3
language: generic
branches:
    only:
    - master
    - /^v\d.*/
env:
- TOXENV=py2 PYTHON=python
- TOXENV=py2-flake8 PYTHON=python
- TOXENV=py3 PYTHON=python3

before_install:
- brew update
install:
- brew install $PYTHON
- $PYTHON -m pip install tox
before_script:
- umask 0022
script:
- tox

deploy:
  provider: pypi
  user: tdsmith
  password:
    secure: aMbgpTpEpojo1OYq8JDhg3Qgo3/c5BoKGeHwm0UJ070kn7sR3K4zwsQ1ybq9DsM6oL+Nv9vAfbyyQmHyuDf0OoXt0nEPR/vkbwURrrXONmQ5NUvLULnQTdfwvNbHY3TaQlTbrloCVhr5CECDKckd+6SHcJDfjwsSaVK0wSWNq8Y=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: tdsmith/homebrew-pypi-poet
    condition: $TOXENV = py2
