language: python
sudo: false
branches:
    only:
    - master
    - /^v\d.*/
matrix:
    include:
        - env: TOXENV=py27
          python: "2.7"
        - env: TOXENV=py35
          python: "3.5"
install:
- git clone --depth=1 https://github.com/Homebrew/brew.git
- pip install tox
before_script:
- export PATH=$PATH:$PWD/brew/bin
- umask 0022
script:
- tox
deploy:
  provider: pypi
  user: tdsmith
  password:
    secure: aMbgpTpEpojo1OYq8JDhg3Qgo3/c5BoKGeHwm0UJ070kn7sR3K4zwsQ1ybq9DsM6oL+Nv9vAfbyyQmHyuDf0OoXt0nEPR/vkbwURrrXONmQ5NUvLULnQTdfwvNbHY3TaQlTbrloCVhr5CECDKckd+6SHcJDfjwsSaVK0wSWNq8Y=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: tdsmith/homebrew-pypi-poet
    condition: $TOXENV = py27
